# Generated by Django 2.0.2 on 2018-02-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail_rekomendasi',
            fields=[
                ('id_detail_rekomendasi', models.AutoField(primary_key=True, serialize=False)),
                ('hasil_rekomendasi', models.FloatField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='keranjang_pembelian',
            fields=[
                ('id_keranjang', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('username_pelanggan', models.CharField(max_length=250)),
                ('password_pelanggan', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='prediksi',
            fields=[
                ('id_prediksi', models.AutoField(primary_key=True, serialize=False)),
                ('hasil_prediksi', models.FloatField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=250)),
                ('kategori_produk', models.CharField(max_length=250)),
                ('stok_produk', models.IntegerField(verbose_name=250)),
                ('harga_produk', models.IntegerField(verbose_name=250)),
                ('rating_produk', models.IntegerField(verbose_name=250)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id_rating', models.AutoField(primary_key=True, serialize=False)),
                ('rating_pelanggan', models.FloatField(max_length=250)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pelanggan')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produk')),
            ],
        ),
        migrations.CreateModel(
            name='rekomendasi',
            fields=[
                ('id_rekomendasi', models.AutoField(primary_key=True, serialize=False)),
                ('id_detail_rekomendasi', models.FloatField(max_length=250)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pelanggan')),
                ('id_prediksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.prediksi')),
            ],
        ),
        migrations.AddField(
            model_name='prediksi',
            name='id_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rating'),
        ),
        migrations.AddField(
            model_name='keranjang_pembelian',
            name='id_pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pelanggan'),
        ),
        migrations.AddField(
            model_name='keranjang_pembelian',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produk'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produk'),
        ),
    ]
