# Generated by Django 2.0.2 on 2018-03-24 16:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180324_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keranjang_pembelian',
            name='id_pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggan', to='store.Pelanggan'),
        ),
        migrations.AlterField(
            model_name='keranjang_pembelian',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='store.Produk'),
        ),
        migrations.AlterField(
            model_name='prediksi',
            name='id_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Rating'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga_produk',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default=Decimal('0.0'), default_currency='EUR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='store.Kategori'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Pelanggan'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Produk'),
        ),
        migrations.AlterField(
            model_name='rekomendasi',
            name='id_pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Pelanggan'),
        ),
        migrations.AlterField(
            model_name='rekomendasi',
            name='id_prediksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Prediksi'),
        ),
    ]
